# File: .github/workflows/autopost.yml

name: 'Scheduled Auto Blogger'

# Yeh workflow har 3 ghante mein ek baar chalega (Minutes, Hour, Day-of-Month, Month, Day-of-Week)
on:
  schedule:
    # Har 3 ghante mein chalao (0 */3 * * *)
    - cron: '0 */3 * * *'
  # Manual testing ke liye, aap isse GitHub interface se bhi chala sakte hain
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Agar script 5 minute se zyada chala toh band ho jayega

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        # Aapke code ke liye Node.js ka version set karein
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Auto Post Script
        # Saare zaroori environment variables (Secrets) yahan pass kiye jayenge
        env:
          # OpenAI API Key (Token kharch yahan se hoga)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          # Blogger/Google OAuth Secrets
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          
          # App Settings (Code mein set kiye gaye hain, yahan override kar sakte hain)
          GSMARENA_RSS: ${{ secrets.GSMARENA_RSS }}
          MAX_ITEMS_PER_RUN: 1 # Confirming the 1-item limit for safety
          MODE: once # Workflow mein har run ke baad script ko band kar dega
        
        # Script ko chalao
        run: node app.js
